r_packages:
  - knitr
  - markdown
  - rmarkdown
  - xaringan
  - DT
  - pagedown
  - tidyverse
  - spatstat
  - sf
  - spsurvey
  - MBHdesign
r_github_packages:
  - hadley/emo
  - gadenbuie/xaringanExtra
